### ISSUE TITLE
Can't add channels

### ISSUE THREAD

**Issue by tmpta-napert** [melalawi/GlobalTwitchEmotes#27]
Browser: Firefox 76.0b8 (64 bit)
extension version: 1.4.1003 release (built from guide)
Whenever i try to add channels via importing settings or adding them manually they appear to be added successfully, but whenever i refresh the options page all the channels disappear completely
I also noticed when i enable "Pause on breakpoints" in the firefox debugger and try to save the settings it catches an exception "TypeError: can't access property "header", e is undefined" on line 43 in file options.js

**Comment by melalawi** [comment]
I can't seem to reproduce this. What kind of channels are you adding? (e.g. twitchtv, bttv, ffz)

**Comment by tmpta-napert** [comment]
any, whenever i click on "Save Settings" it doesn't save and the firefox debugger catches "TypeError: e is undefined" in options.js

**Comment by StephGbzh** [comment]
I confirm this behavior: I was using Chrome until this week-end and one day last week I saw that there were fewer emotes than before. I opened the GTE settings and everything was gone, no channel, not even a checkbox checked anymore. After I added some channels back, I saved and reloaded the twitch page but nothing improved so I restarted Chrome but again all the settings were gone.

Yesterday I installed the last version of Ubuntu 20.04 on my new SSD and I tried to use Firefox and GTE to watch Twitch: the exact same thing happened and since I saw the message above, I also activated the "Pause on exception" in Firefox Debugger and indeed I get this: 

TypeError: e is undefined

And it happens apparently here on line 43 of option.js:

`...function onMessage(e){"settings"===e.header&&...`

To reproduce, just open the settings page and (try to) Save Settings immediately.

**Comment by Siurczek** [comment]
This bug occurs on chrome too but I discovered that banned forsen channel is doing that. After deleting forsen from settings its starts working again. Also majority of gif emotes doesn't work for me

**Comment by richowen** [comment]
nothing is being saved for me either, I check all the boxes and add channels, then click save, on refresh everything is blank agian.

**Comment by Serfin** [comment]
Looks like this issue **https://github.com/melalawi/GlobalTwitchEmotes/issues/31** It was fixed recently so maybe it fixed your problems.

**Comment by richowen** [comment]
think it did yeh, nice

**Comment by tmpta-napert** [comment]
updating to 1.4.1007 has fixed the issue
